services:
  server:
    image: node:22
    ports:
      - 3000:3000
    volumes:
      - ./code/server:/app
    working_dir: /app
    # c'est une bidouille pour garder le conteneur ouver, vu qu'ont lui a dit qu'ont va utiliser le terminale
    tty: true
  # service gérant le serveur MySQL
  mysql:
    image: mysql:9
    ports:
      - 3306:3306
    volumes:
      - ./code/server/mysql:/app
      - ./mysql-db:/var/lib/mysql
    working_dir: /app
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
  # le service gérant le serveur MongoDB
  mongodb: 
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - ./code/server/mongodb:/app
      - ./mongodb-db:/data/db
    working_dir: /app
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    restart: always
