# nom du workflow 
name: Garage CI/CD

# déclenchement du workflow
on: workflow_dispatch

# tâches
jobs:

    # nom de la tâche
    CI:

        # type d'environnement
        runs-on: ubuntu-latest

        steps:
            - 
                name: Récupérer le dépôt GitHub

                # executer une commande prédèfinie : checkout
                uses: actions/checkout@v4

            -
                name: installer les dépendances de Node

                # executer une commande personelle : run
                run: |
                    cd code/server
                    npm ci