# nom du workflow 
name: Garage CI/CD

# déclenchement du workflow
on: workflow_dispatch

# tâches
jobs:

    # nom de la tâche
    CI:

        # type d'environnement
        runs-on: ubuntu-latest

        steps:
            - 
                name: Récupérer le dépôt GitHub

                # executer une commande prédèfinie : checkout
                uses: actions/checkout@v4

            -
                name: installer les dépendances de Node

                # executer une commande personelle : run
                run: |
                    cd code/server
                    npm ci

            -
                name: Compiler TypeScript en JavaScript
                run: |
                    cd code/server
                    rm -rf dist
                    npm run compile

            -
                name: installer la basse de données dans le serveur MySQL
                run: |
                    sudo service mysql start
                    cd code/server/mysql
                    mysql -uroot -proot -e 'SOURCE garage.test.sql;'
                    mysql -uroot -proot -e 'SHOW DATABASES;'
                    mysql -uroot -proot -e 'USE garage_test; TABLE garage_test.brand;'